// <auto-generated />
using System;
using DNPExercises10DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DNPExercises10DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190114202938_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DNPExercises10DataAccess.Data.Entities.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("Color");

                    b.Property<string>("FavoriteDish");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("cats");
                });

            modelBuilder.Entity("DNPExercises10DataAccess.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("OrderDate");

                    b.Property<string>("OrderNumber");

                    b.HasKey("Id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("DNPExercises10DataAccess.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("catId");

                    b.Property<int?>("orderId");

                    b.Property<int>("quantity");

                    b.HasKey("Id");

                    b.HasIndex("catId");

                    b.HasIndex("orderId");

                    b.ToTable("orderItems");
                });

            modelBuilder.Entity("DNPExercises10DataAccess.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("DNPExercises10DataAccess.Data.Entities.Cat", "cat")
                        .WithMany()
                        .HasForeignKey("catId");

                    b.HasOne("DNPExercises10DataAccess.Data.Entities.Order", "order")
                        .WithMany("Items")
                        .HasForeignKey("orderId");
                });
#pragma warning restore 612, 618
        }
    }
}
